### ISSUE TITLE
Include problems

### ISSUE THREAD

**Issue by CristinaCristescu** [ramosian-glider/clang-kernel-build#2]
Hi,

This is great work, thanks!
 I just have a problem with the include path. I have followed the steps, but at Step 4 I encounter the following issue when I run: make CC=`pwd`/../clang_wrapper.py 2>&1 | tee build.log
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
  HOSTCC  arch/x86/tools/relocs_32.o
In file included from arch/x86/tools/relocs_32.c:1:
arch/x86/tools/relocs.h:12:10: fatal error: 'elf.h' file not found
#include <elf.h>
         ^
1 error generated.

If I look for the file I find a couple of versions of it in the linux-stable directory.

Any ideas?

Thanks!

**Comment by ramosian-glider** [comment]
Which kernel config you're using?

sent from phone

**Comment by CristinaCristescu** [comment]
It is Linux/x86 4.11.0-rc2 Kernel Configuration. 
I just used the "make CC=$CLANG_PATH/clang defconfig" command for configuration.
I have tried on different platforms: mac OS, Ubuntu, Debian, but all resulted in file not found. Although the platform should not matter since the build is self-contained, right?

**Comment by ramosian-glider** [comment]
Right, my question was about the contents of .config (whether you've changed it anyhow after running defconfig; I'm assuming no.

Are you able to build the kernel without Clang by just running `make` without `CC`?

I suspect your system is really missing the elf.h header. Maybe you forgot to install libc6-dev?
(I should have probably included the list of packages required to build the kernel, but usually kernel developers have them already, so I didn't bother :))

**Comment by CristinaCristescu** [comment]
Correct assumption, I haven't changed it. 

So the elf problem is a mac os problem it seems. I have managed to build the kernel even with Clang even on a Debian system. So Step 4 in the README works :) but the problem is when I run the clang_wrapper.py from the HACKING section that crashes. I want to run the wrapper because I need al the compilation commands so that I can use clang's AST dumper. 

The python script fails when calling the subprocess on new_args. I have tried to print the value of new_args. I attach the log.

Thanks!
[build.txt](https://github.com/ramosian-glider/clang-kernel-build/files/1058474/build.txt)

**Comment by ramosian-glider** [comment]
Haha, there's a hardcoded path to Clang in clang_wrapper.py.

I've updated the wrapper, please take another look.

Regarding elf.h on Mac OS, this may help: http://plattanimattan.blogspot.de/2010/04/cross-compiling-linux-on-mac-osx.html

**Comment by CristinaCristescu** [comment]
Yes, it works now! Thanks for your promptness :)

**Comment by ramosian-glider** [comment]
Great :)
