### ISSUE TITLE
Switch back to linux-stable (Linux 4.13 released)

### ISSUE THREAD

**Issue by tpimh** [ramosian-glider/clang-kernel-build#4]
Both 4.13-rc7 and stable 4.13 fail for me with the latest clang when compiling `arch/x86/kernel/setup.c`, but this is a problem of the toolchain (clang segfaults), not the kernel.

**Comment by ramosian-glider** [comment]
Done.
Which Clang version are you using? Guess that's not the Chromium one?

**Comment by tpimh** [comment]
It is Chromium's build. When I tried it was `trunk 312679`. Tries to compile `setup.c` and fails with the following message:

    clang: error: unable to execute command: Segmentation fault (core dumped)
    clang: error: clang frontend command failed due to signal (use -v to see invocation)
    clang version 6.0.0 (trunk 312679)
    Target: x86_64-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /opt/build/clang-kernel-build/third_party/llvm-build/Release+Asserts/bin

I should probably collect more information and submit decent bug report to LLVM's bugzilla.

**Comment by ramosian-glider** [comment]
Right now the Chromium Clang version is 313222, could you try that, please?

**Comment by tpimh** [comment]
Just tested, it compiles fine.

**Comment by ramosian-glider** [comment]
Ok, closing then.
