### ISSUE TITLE
KVM seems to work with 4.14-rc2

### ISSUE THREAD

**Issue by etherealvisage** [ramosian-glider/clang-kernel-build#5]
Hi,

I compiled 4.14-rc2 with clang and KVM seems to work inside VMWare Player: the system doesn't hang on boot, and qemu can run another VM inside, and the innermost VM reports running with KVM virtualization. It might be worth removing or qualifying the "Known Problems" entry in the README re: KVM.

 - ethereal

**Comment by ramosian-glider** [comment]
Which config options did you enable in addition to defconfig?
In particular, was CONFIG_KVM enabled?

**Comment by etherealvisage** [comment]
The [full config is here](https://gist.github.com/etherealvisage/2a3ab0dcf632c75505154eee766a01a5), which is basically a stripped-down kernel to run inside VMWare, though it runs well on bare metal as well. So there's lots of changes from defconfig --- I'll try again with a more default configuration in a bit to see if that works.

**Comment by etherealvisage** [comment]
Same thing with a default configuration + CONFIG_KVM enabled. Boots and appears to work correctly.

**Comment by ramosian-glider** [comment]
I've taken another look. `make defconfig; make kvmconfig` still doesn't work, but that happens because of CONFIG_PARAVIRT, not CONFIG_KVM (surprisingly `make kvmconfig` doesn't even set CONFIG_KVM).
I've updated the docs, thanks for noticing this!
