### ISSUE TITLE
compiler lacks asm-goto support

### ISSUE THREAD

**Issue by zhanggenex** [ramosian-glider/clang-kernel-build#7]
Hi, I tried to build linux-5.0 with clang-7.0.0, but came out error: **Compiler lacks asm-goto support.**
I googled for this problem, and https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Asm-Goto-Merged says this asm-goto support for clang is already merged.
So could you please send me the download site, since I didn't  find this version on the official website.
Thanks,
Alex

**Comment by ramosian-glider** [comment]
As of recently, Clang supports asm-goto well enough to build an x86 kernel.
More information is at https://github.com/ClangBuiltLinux/linux/issues/6
