### ISSUE TITLE
Create_os_image.sh link return error 404

### ISSUE THREAD

**Issue by asha15** [ramosian-glider/clang-kernel-build#8]
Hi @ramosian-glider, 
`wget https://raw.githubusercontent.com/google/sanitizers/master/address-sanitizer/kernel_buildbot/create_os_image.sh` returns error 404. Can i know the new link? also i was executed the below code since the URL is not working but it didn't create the wheezy.img. Could you help me to resolve this ? 

```
# Perform these steps instead of Step 4 above.
cd $WORLD/linux-stable
make CC=$CLANG_PATH/clang defconfig
make CC=`pwd`/../clang_wrapper.py 2>&1 | tee build.log
``` 
Thank you!

**Comment by ownia** [comment]
take a look at this.
https://github.com/google/sanitizers/blob/3d102187c4b096a8b32b62558d8aca6ab633d406/address-sanitizer/kernel_buildbot/create_os_image.sh
